package co.simplon.everydaybetterbusiness.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@Table(name = "t_habits")
@AllArgsConstructor
@NoArgsConstructor
public class HabitEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter(AccessLevel.NONE)
    @Column(name = "id_habit")
    private Long id;

    @Column(name = "habit_name", nullable = false)
    private String habitName;

    @Column(name = "description")
    private String description;

    @Column(name = "is_positive", nullable = false, columnDefinition = "boolean default true")
    private Boolean isPositive;

    @Column(name = "reset_counter", nullable = false)
    private String resetCounter;

    @Column(name = "label_name")
    private String labelName;


    @SuppressWarnings("unused")
    private void setId(long id) {
        this.id = id;
    }
    //Todo Thao
    //Why use Lombok? for id: @Setter(AccessLevel.NONE) setId will not be generated by Lombok

}
